"""
Core structural configurations and layer parameters for the Visual GRNet (VGN) model.

This module encapsulates configuration parameters using Python dataclasses to govern 
network topology properties (recurrent dimensions, adapter bottlenecks, optimization schedulers). 
It also provides native Keras 3 serializable learning rate schedules to support stabilization 
phases during early training epochs.
"""

import random
import time
import os
import math
from pathlib import Path
from datetime import datetime
from typing import Union, List
from dataclasses import dataclass, field

import numpy as np
import tensorflow as tf
from keras import ops
from keras.initializers import Constant
from keras.regularizers import Regularizer
from keras.models import Model, Sequential
from keras.optimizers import Adam
from keras.optimizers.schedules import LearningRateSchedule
from keras.layers import Input, Dense, LSTM, LayerNormalization, Dropout, Masking, AlphaDropout, Bidirectional, Activation
from attention_extraction_layers import AttentionWeights, ContextVector
from keras.callbacks import Callback, EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from keras.losses import Loss, BinaryCrossentropy
from keras.regularizers import L2
from keras.models import load_model
from keras.metrics import AUC, Precision, Recall, F1Score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, average_precision_score
from tensorflow.data import Dataset  # type: ignore
from keras.saving import register_keras_serializable

from sequence_generator import SequenceDatasetMultiPerc
from embedding_dataset import EmbeddingSequenceMultiPerc, EmbeddingSequence

seed = int(os.getenv('EXPERIMENT_SEED', 43))
tf.random.set_seed(seed)
np.random.seed(seed)


@dataclass
class EncoderParams:
    """
    Configuration parameters for the vision-based feature encoder network.

    Parameters
    ----------
    embedding_dim : int, default 256
        The dimensionality of the latent state space generated by the encoder block.
    trainable : bool, default False
        Determines if the encoder weights are frozen or optimized during backpropagation.
    dizionario_goal : dict, optional
        A dictionary mapping fluent string tokens to discrete index integers.
    goals : dict, optional
        Nested dictionary tracking sequence keys to active ground truth target fluents.
    """
    embedding_dim: int = 256
    trainable: bool = False
    dizionario_goal: dict|None = None
    goals: dict|None = None


@dataclass
class AdapterParams:
    """
    Configuration parameters for the linear adapter projection layer.

    Acts as a dimensionality alignment bottleneck between latent image embeddings 
    and the recurrent network hidden processing units.

    Parameters
    ----------
    use_adapter : bool, default False
        Flag indicating if the adapter projection tensor should be built into the pipeline.
    adapt_dropout : float, default 0.0
        The dropout regularization rate applied to the adapter layer activations.
    adapt_factor : int, default 5
        The scaling factor regulating dimensional reduction bottlenecks.
    activation : str, default 'silu'
        String identifier specifying the non-linear activation function.
    """
    use_adapter: bool = False
    adapt_dropout: float = 0.0
    adapt_factor: int = 5
    activation: str = 'silu'


@dataclass
class RecurrentParams:
    """
    Configuration parameters for the recurrent tracking sub-network.

    Parameters
    ----------
    units : int, default 64
        The number of hidden units allocated to the recurrent cells.
    activation : str, default 'linear'
        The type of non-linear structural activation mapping function to invoke.
    dropout : float, default 0.0
        The dropout rate applied to input connections.
    recurrent_dropout : float, default 0.0
        The dropout rate applied to internal recurrent state connections.
    type : str, default 'lstm'
        The tracking engine cell variant type.
    """
    units: int = 64
    activation: str = 'linear'
    dropout: float = 0.0
    recurrent_dropout: float = 0.0
    type: str = 'lstm'


@dataclass
class ImageParams:
    """
    Structural parameters mapping source imagery dimensions.

    Parameters
    ----------
    height : int, default 256
        Target vertical pixel bounds configuration.
    width : int, default 256
        Target horizontal pixel bounds configuration.
    channels : int, default 3
        Color space layout coordinate counts (e.g., 3 for RGB, 1 for Grayscale).
    """
    height: int = 256
    width: int = 256
    channels: int = 3


@dataclass
class DatasetParams:
    """
    Configuration parameters tracking dataset parameters and scaling variables.

    Parameters
    ----------
    max_sequence_dim : int, default 75
        The maximum allowed sequence length acting as the padding or truncation boundary.
    num_classes : int, default 506
        The total dimensionality of the target goal vector space.
    min_percentage : float, default 0.3
        The lower bound fraction constraint for uniform state sampling.
    max_percentage : float, default 0.7
        The upper bound fraction constraint for uniform state sampling.
    ignore_last_n_states : int, default 0
        The count of terminal sequence frames to drop during data loading.
    batch_size : int, default 64
        The slice scaling size tracking packed matrices per optimization step.
    dataset_version : str, optional
        String identifier version tag tracking the active embeddings partition variants on disk.
    normalize : bool, default False
        If True, enforces global Z-score standard scaling on incoming input representations.
    """
    max_sequence_dim: int = 75
    num_classes: int = 506
    min_percentage: float = 0.3
    max_percentage: float = 0.7
    ignore_last_n_states: int = 0
    batch_size: int = 64
    dataset_version: Union[str, None] = None
    normalize: bool = False


@register_keras_serializable()
class LinearWarmup(LearningRateSchedule):
    r"""
    Serializable linear learning rate warmup schedule for backend-agnostic Keras 3.

    Linearly scales the learning rate from a baseline minimum threshold up to a targeted 
    peak value over a fixed number of absolute steps. This initialization technique prevents 
    early gradient explosion faults when optimizing recurrent architectures configured with 
    unbounded linear activations.

    The learning rate calculation at step $t$ is defined as:

    $$\eta_t = \eta_{\text{min}} + (\eta_{\text{peak}} - \eta_{\text{min}}) \times \frac{t}{T_{\text{warmup}}}$$

    Parameters
    ----------
    peak_lr : float
        The maximum target learning rate magnitude achieved at the completion of the warmup phase.
    warmup_steps : int
        The absolute step horizon constraint over which the learning rate transitions to its peak.
    min_lr : float, default 1e-5
        The starting baseline floor learning rate magnitude used to initialize the first training step.
    """
    def __init__(self, peak_lr: float, warmup_steps: int, min_lr: float = 1e-5):
        super().__init__()
        self.peak_lr = peak_lr
        self.warmup_steps = warmup_steps
        self.min_lr = min_lr

    def __call__(self, step: tf.Tensor) -> tf.Tensor:
        """
        Compute the dynamic operational learning rate matching the active training step pointer.

        Parameters
        ----------
        step : tf.Tensor
            The scalar tracking step pointer parsed from the current global optimizer cycle.

        Returns
        -------
        tf.Tensor
            A scalar tensor tracking the computed objective learning rate value.
        """
        step = ops.cast(step, 'float32') # type: ignore
        warmup_steps = float(self.warmup_steps)

        warmup_lr = self.min_lr + (self.peak_lr - self.min_lr) * (step / warmup_steps)
        return ops.where(step < warmup_steps, warmup_lr, self.peak_lr) # type: ignore

    def get_config(self) -> dict:
        """
        Serialize the schedule parameter constraints into a metadata mapping.

        Returns
        -------
        dict
            A key-value serialization dictionary dictionary mapping tracking variables.
        """
        return {
            'peak_lr': self.peak_lr,
            'warmup_steps': self.warmup_steps,
            'min_lr': self.min_lr,
        }


@register_keras_serializable()
class WarmupCosineDecay(LearningRateSchedule):
    r"""
    Serializable Learning Rate schedule with Linear Warmup followed by Cosine Decay 
    for backend-agnostic Keras 3.

    Parameters
    ----------
    peak_lr : float
        Maximum target learning rate achieved at the end of warmup.
    warmup_steps : int
        Number of steps for the linear warmup phase.
    decay_steps : int
        Number of steps for the cosine decay phase after warmup.
    min_lr : float, default 1e-5
        Baseline learning rate floor used at start of warmup and end of decay.
    """
    def __init__(
        self, 
        peak_lr: float, 
        warmup_steps: int, 
        decay_steps: int, 
        min_lr: float = 1e-5,
        **kwargs
    ):
        super().__init__(**kwargs)
        self.peak_lr = peak_lr
        self.warmup_steps = warmup_steps
        self.decay_steps = decay_steps
        self.min_lr = min_lr

    def __call__(self, step):
        step = ops.cast(step, 'float32')
        warmup_steps = float(self.warmup_steps)
        decay_steps = float(self.decay_steps)

        warmup_lr = self.min_lr + (self.peak_lr - self.min_lr) * (step / warmup_steps)

        decay_step = ops.clip(step - warmup_steps, 0.0, decay_steps)
        cosine_decay = 0.5 * (1.0 + ops.cos(math.pi * (decay_step / decay_steps)))
        decay_lr = self.min_lr + (self.peak_lr - self.min_lr) * cosine_decay

        return ops.where(step < warmup_steps, warmup_lr, decay_lr)

    def get_config(self) -> dict:
        config = super().get_config()
        config.update({
            'peak_lr': self.peak_lr,
            'warmup_steps': self.warmup_steps,
            'decay_steps': self.decay_steps,
            'min_lr': self.min_lr,
        })
        return config


@dataclass
class LRSchedulerParams:
    """
    Configuration parameters managing optimization scheduler states.

    Parameters
    ----------
    use_warmup : bool, default True
        If True, binds a linear warmup scheduler phase to early optimization steps.
    min_lr : float, default 1e-5
        The initialization floor learning rate magnitude boundary.
    warmup_epochs : int, default 5
        The training epoch length budget over which the warmup ramp executes.
    steps_per_epoch : int, default 600
        The step density parameter used to map epoch bounds to absolute step limits.
    """
    use_warmup: bool = True
    use_decay: bool = False
    min_lr: float = 1e-5
    warmup_epochs: int = 5
    steps_per_epoch: int = 600


@dataclass
class OptimizerParams:
    """
    Configuration parameters managing tracking optimizer settings.

    Parameters
    ----------
    learning_rate : float, default 0.001
        The target optimization learning rate magnitude parameter.
    lr_scheduler : LRSchedulerParams, default LRSchedulerParams()
        Nested dataclass configuration specifying learning rate adaptation rules.
    clipnorm : float, optional, default 1.0
        The maximum global gradient norm boundary used to stabilize optimization via gradient clipping.
    """
    learning_rate: float = 0.001
    lr_scheduler: LRSchedulerParams = field(default_factory=LRSchedulerParams)
    clipnorm: Union[float, None] = 1.0


@dataclass
class NetworkParams:
    """
    Unified top-level parameter aggregator tracking holistic Visual GRNet models.

    Parameters
    ----------
    model_name : str
        The categorical identifier string tagging the target model instantiation.
    loss_function : str or keras.losses.Loss, default 'binary_crossentropy'
        The core objective metric minimized during model optimization routines.
    embedding_dim : int, default 256
        The operational feature size mapping spatial vector properties.
    recurrent : RecurrentParams, default RecurrentParams()
        Nested parameter dataclass tracking recurrent layer properties.
    image : ImageParams, default ImageParams()
        Nested parameter dataclass tracking image dimensional properties.
    dataset : DatasetParams, default DatasetParams()
        Nested parameter dataclass tracking partition metadata profiles.
    optimizer : OptimizerParams, default OptimizerParams()
        Nested parameter dataclass tracking optimizer variables.
    adapter : AdapterParams, default AdapterParams()
        Nested parameter dataclass tracking projection adapter settings.
    output_regularizer : keras.regularizers.Regularizer, optional, default None
        Optional regularizer applied to stabilize downstream dense classification mappings.
    use_bidirectional : bool, default False
        If True, wraps recurrent architectures inside Bidirectional wrappers.
    """
    model_name: str
    loss_function: Union[str, Loss] = 'binary_crossentropy'
    embedding_dim: int = 256
    recurrent: RecurrentParams = field(default_factory=RecurrentParams)
    image: ImageParams = field(default_factory=ImageParams)
    dataset: DatasetParams = field(default_factory=DatasetParams)
    optimizer: OptimizerParams = field(default_factory=OptimizerParams)
    adapter: AdapterParams = field(default_factory=AdapterParams)
    output_regularizer: Union[Regularizer, None] = None
    use_bidirectional: bool = False

def build_network(network_params: Union[NetworkParams, None] = None, bias_initializer: Union[np.ndarray, None] = None) -> Model:
    """
    Instantiate and compile the Visual GRNet (VGN) sequential network model.

    This function builds a Keras Functional Model mapping structural pipelines including: 
    an optional multi-layer linear projection adapter with an explicit residual skip connection 
    and layer normalization, a masked recurrent tracking block (LSTM or Bidirectional LSTM), 
    a sequential token-level scoring mechanism (AttentionWeights), and a dense classification 
    head initialized with frequency-derived empirical bias priors.

    Parameters
    ----------
    network_params : Optional[NetworkParams], default None
        The configuration dataclass tracking topological variables, structural layer hyperparameters, 
        and optimization rules. If None, instantiates a default structural instance.
    bias_initializer : Optional[np.ndarray], default None
        A 1D array of shape (num_classes,) containing data-driven empirical joint frequency 
        weights to initialize output biases. Allocates zeros if not provided.

    Returns
    -------
    keras.models.Model
        A compiled instance of the Keras Functional Model ready for optimization loops.
    """    
    if network_params is None:
        network_params = NetworkParams(model_name='visual-grnet')

    embedding_dim = network_params.embedding_dim
    recurrent_params = network_params.recurrent
    optimizer_params = network_params.optimizer
    adapter_params = network_params.adapter
    dataset_params = network_params.dataset
    
    inputs = Input(shape=(dataset_params.max_sequence_dim, embedding_dim), name='input')

    if adapter_params.use_adapter:
        adapt_factor = adapter_params.adapt_factor
        adapt_dropout = adapter_params.adapt_dropout
        
        x = Dense(embedding_dim * adapt_factor, activation=adapter_params.activation, name='adapter_up')(inputs)
        if adapt_dropout > 0:
            x = Dropout(adapt_dropout, name='dropout_1')(x)
            
        x = Dense(embedding_dim * adapt_factor, activation=adapter_params.activation, name='adapter_h')(x)
        if adapt_dropout > 0:
            x = Dropout(adapt_dropout, name='dropout_2')(x)
            
        x = Dense(embedding_dim, name='adapter_down')(x)
        x = x + inputs
        x = LayerNormalization(name='layer_norm')(x)
    else:
        x = inputs
    
    mask = ops.any(ops.not_equal(inputs, -100.0), axis=-1)
    
    lstm = LSTM(
        activation=recurrent_params.activation,
        units=recurrent_params.units,
        dropout=recurrent_params.dropout,
        recurrent_dropout=recurrent_params.recurrent_dropout,
        return_sequences=True,
        name='lstm'
    )

    if network_params.use_bidirectional:
        recurrent_layer = Bidirectional(lstm)(x, mask=mask)
    else:
        recurrent_layer = lstm(x, mask=mask)
    
    attention_weights = AttentionWeights(dataset_params.max_sequence_dim, name='attention_weights')(recurrent_layer, mask=mask)
    context_vector = ContextVector()([recurrent_layer, attention_weights])

    if bias_initializer is None:
        bias_initializer = np.zeros(shape=(dataset_params.num_classes,))

    outputs = Dense(
        dataset_params.num_classes, 
        activation='sigmoid', 
        kernel_regularizer=network_params.output_regularizer,
        bias_initializer=Constant(bias_initializer), # type: ignore
        name='output'
    )(context_vector)

    model = Model(inputs=inputs, outputs=outputs, name=network_params.model_name)

    if optimizer_params.lr_scheduler.use_warmup and not optimizer_params.lr_scheduler.use_decay:
        lr_schedule = LinearWarmup(
            peak_lr=optimizer_params.learning_rate,
            warmup_steps=optimizer_params.lr_scheduler.warmup_epochs * optimizer_params.lr_scheduler.steps_per_epoch,
            min_lr=optimizer_params.lr_scheduler.min_lr
        )
    elif optimizer_params.lr_scheduler.use_warmup and optimizer_params.lr_scheduler.use_decay:
        lr_schedule = WarmupCosineDecay(
            peak_lr=optimizer_params.learning_rate,
            warmup_steps=optimizer_params.lr_scheduler.warmup_epochs * optimizer_params.lr_scheduler.steps_per_epoch,
            decay_steps=optimizer_params.lr_scheduler.steps_per_epoch * (50 - optimizer_params.lr_scheduler.warmup_epochs),
            min_lr=optimizer_params.lr_scheduler.min_lr
        )
    else:
        lr_schedule = optimizer_params.learning_rate

    model.compile(
        optimizer=Adam(
            learning_rate=lr_schedule, # type: ignore
            clipnorm=optimizer_params.clipnorm,
        ), 
        loss=network_params.loss_function,
        metrics=[
            AUC(
                name='pr_auc', 
                multi_label=True, 
                num_labels=dataset_params.num_classes, 
                curve='PR', 
                num_thresholds=500
            )
        ]
    )

    return model

@dataclass
class ModelCheckpointParams:
    """
    Configuration parameters for the Keras ModelCheckpoint callback.

    Parameters
    ----------
    use_callback : bool, default True
        If True, instantiates and appends the checkpoint callback to the training loop.
    monitor : str, default 'val_loss'
        The target metric tracked to evaluate checkpoint optimization.
    mode : str, default 'auto'
        One of {'auto', 'min', 'max'}. Determines whether the tracked metric should be 
        minimized or maximized.
    save_best_only : bool, default True
        If True, disk write operations are only executed when the tracked metric improves.
    save_weights_only : bool, default False
        If True, only the model weights are stored, otherwise the full model is saved.
    """
    use_callback: bool = True
    monitor: str = 'val_loss'
    mode: str = 'auto'
    save_best_only: bool = True
    save_weights_only: bool = False


@dataclass
class EarlyStoppingParams:
    """
    Configuration parameters for the Keras EarlyStopping callback.

    Parameters
    ----------
    use_callback : bool, default True
        If True, instantiates and appends the early stopping callback to the training loop.
    monitor : str, default 'val_loss'
        The target validation metric tracked to evaluate optimization stagnation.
    mode : str, default 'min'
        One of {'auto', 'min', 'max'}. Direction of optimization for the monitored metric.
    patience : int, default 10
        The number of training epochs with no training variance improvement before training terminates.
    min_delta : float, default 1e-5
        The minimum threshold configuration quantified to register an improvement step.
    verbose : int, default 2
        The explicit verbosity mode.
    start_from_epoch : int, default 10
        The concrete training epoch pointer baseline before convergence testing activates.
    """
    use_callback: bool = True
    monitor: str = 'val_loss'
    mode: str = 'min'
    patience: int = 10
    min_delta: float = 1e-5
    verbose: int = 2
    start_from_epoch: int = 10


@dataclass
class ReduceLROnPlateauParams:
    """
    Configuration parameters for the Keras ReduceLROnPlateau callback.

    Parameters
    ----------
    use_callback : bool, default True
        If True, instantiates and appends the scheduler callback to the training loop.
    monitor : str, default 'val_loss'
        The validation metric monitored to track convergence plateaus.
    mode : str, default 'min'
        One of {'auto', 'min', 'max'}. Direction of optimization for the monitored metric.
    factor : float, default 0.5
        The multiplicative scaling coefficient factor applied to damp the active learning rate.
    patience : int, default 5
        The number of training epochs with no variance improvement before reducing the learning rate.
    min_lr : float, default 1e-5
        The absolute floor lower learning rate magnitude boundary.
    min_delta : float, default 1e-4
        The minimum variance delta required to reset the plateau validation steps counter.
    verbose : int, default 1
        The verbosity level layout configuration tracking update actions.
    """
    use_callback: bool = True
    monitor: str = 'val_loss'
    mode: str = 'min'
    factor: float = 0.5
    patience: int = 5
    min_lr: float = 1e-5
    min_delta: float = 1e-4
    verbose: int = 1


class StaticProgressLogger(Callback):
    """
    Custom Keras Callback for standardized experiment logging and high-resolution profiling.

    Tracks absolute operational wall-clock execution limits, displays structural metrics 
    separated by training/validation contexts, and profiles host batch computation times 
    using high-resolution hardware timers (`time.perf_counter`).

    Parameters
    ----------
    batch_logging : bool, default False
        If True, activates sub-epoch profiling loops at discrete step intervals.
    batch_logging_steps : Optional[int], default None
        The scale factor coefficient tracking the frequency of intra-epoch printing.
    """
    def __init__(self, batch_logging: bool = False, batch_logging_steps: Union[int, None] = None):
        if batch_logging:
            self.batch_logging = batch_logging
            self.batch_logging_steps = batch_logging_steps
        else:
            self.batch_logging = self.batch_logging_steps = None
        super().__init__()

    def on_train_begin(self, logs=None):
        self.step_times = []
        print(f"\n{'='*60}")
        print(f"BEGIN TRAINING: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"{'='*60}\n", flush=True)

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_start_time = time.time()
        print(f'\nStarting Epoch {epoch + 1:02d}')

    def on_epoch_end(self, epoch, logs=None):
        duration = time.time() - self.epoch_start_time
        now = datetime.now().strftime('%H:%M:%S')

        train_metrics_str = ''
        val_metrics_str = ''
        info_str = f"[{now}]\t Epoch {epoch + 1:02d} | Time: {duration:6.2f}s |"
        
        if isinstance(logs, dict):
            for metric, value in logs.items():
                metric_str = f"{value:.6f}" if isinstance(value, float) else value
                if metric.startswith('val'):
                    val_metrics_str += f"{metric}: {metric_str} | "
                else:
                    train_metrics_str += f"{metric}: {metric_str} | "
            
            info_str += f"{train_metrics_str} || {val_metrics_str}"
        
        print(info_str, flush=True)
        
        arr = np.array(self.step_times)
        if arr.size > 0:
            print(f"\t\t\tTime — mean: {arr.mean()*1000:.2f} ms | "
                  f"min: {arr.min()*1000:.2f} ms | max: {arr.max()*1000:.2f} ms")
        self.step_times = []  

    def on_train_end(self, logs=None):
        print(f"\n{'='*60}")
        print(f"END TRAINING: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"{'='*60}\n", flush=True)
    
    def on_train_batch_begin(self, batch, logs=None):
        self._batch_start = time.perf_counter()
    
    def on_train_batch_end(self, batch, logs=None):
        elapsed = time.perf_counter() - self._batch_start
        self.step_times.append(elapsed)
        if self.batch_logging is not None and self.batch_logging_steps is not None:
            if batch % self.batch_logging_steps == 0:
                if batch == 0:
                    print(f"Batch {batch} — {elapsed*1000:.2f} ms")
                else:
                    str_losses = '' 
                    if isinstance(logs, dict):
                        for metric, value in logs.items():
                            metric_str = f"{value:.6f}" if isinstance(value, float) else value
                            str_losses += f"{metric}: {metric_str} | "

                    print(f"Batch {batch} — {sum(self.step_times[-self.batch_logging_steps:])*1000:.2f} ms - {str_losses}", flush=True)


@dataclass
class StaticLoggerParams:
    """
    Configuration parameters managing tracking states for the StaticProgressLogger.

    Parameters
    ----------
    use_callback : bool, default True
        If True, instantiates and appends the custom logging hook.
    batch_logging : bool, default False
        If True, activates sub-epoch profiling loops at discrete step intervals.
    batch_logging_steps : Optional[int], default 10
        The inverse frequency factor calculating macro-step visualization updates.
    """
    use_callback: bool = True
    batch_logging: bool = False
    batch_logging_steps: Union[int, None] = 10


class WeightMonitor(Callback):
    """
    Custom diagnostic Keras Callback tracking parameters distribution metrics.

    Inspects layer-specific parameter matrix variants at structural epoch limits, 
    extracting empirical statistics (mean, variance distribution, absolute bounds) 
    to facilitate debugging vanishing or exploding gradient anomalies.
    """
    def on_epoch_end(self, epoch, logs=None):
        for layer in self.model.layers:   # type: ignore
            for w in layer.trainable_weights:
                vals = w.numpy()
                print(f"{layer.name} {w.name}: mean={vals.mean():.4f}, std={vals.std():.4f}, max={np.abs(vals).max():.4f}")


@dataclass
class CallbackParams:
    """
    Unified parameters dataclass coordinating structural tracking loops hooks.

    Parameters
    ----------
    checkpoint : ModelCheckpointParams, default ModelCheckpointParams()
        Nested configuration tracking checkpointing parameters rules.
    early_stopping : EarlyStoppingParams, default EarlyStoppingParams()
        Nested configuration tracking early convergence criteria rules.
    reduce_lr : ReduceLROnPlateauParams, default ReduceLROnPlateauParams()
        Nested configuration tracking plateau learning rate scheduler rules.
    static_logger : StaticLoggerParams, default StaticLoggerParams()
        Nested configuration tracking custom diagnostic stdout logging parameters rules.
    use_weight_monitor : bool, default True
        If True, links a parameter tensor distribution inspector hook to the pipeline.
    """
    checkpoint: ModelCheckpointParams = field(default_factory=ModelCheckpointParams)
    early_stopping: EarlyStoppingParams = field(default_factory=EarlyStoppingParams)
    reduce_lr: ReduceLROnPlateauParams = field(default_factory=ReduceLROnPlateauParams)
    static_logger: StaticLoggerParams = field(default_factory=StaticLoggerParams) 
    use_weight_monitor: bool = True


def _build_callbacks(
    train_dataset,
    checkpoint_path: Union[Path, None] = None,
    params: Union[CallbackParams, None] = None,
    extra_callbacks: Union[list, None] = None,
) -> list:
    """
    Construct and compile a cohesive list of Keras training callbacks.

    Parses a nested parameters block configuration to systematically evaluate operational 
    flags, instantiates underlying callback instances, computes proper epoch structural step mappings, 
    and appends optional runtime layers.

    Parameters
    ----------
    train_dataset : Sequence or tf.data.Dataset
        The active training data stream provider used to compute batch mapping limits.
    checkpoint_path : Optional[pathlib.Path], default None
        The absolute disk destination destination path targeted for saving optimal model instances.
    params : Optional[CallbackParams], default None
        Unified configuration aggregator management block. Initializes defaults if missing.
    extra_callbacks : Optional[list], default None
        Optional collection of custom external callbacks appended to the training cycle.

    Returns
    -------
    list of keras.callbacks.Callback
        A list tracking fully initialized operational callbacks ready for `model.fit`.
    """    
    params = params or CallbackParams()
    callbacks = []

    if params.early_stopping.use_callback:
        callbacks.append(
            EarlyStopping(
                monitor=params.early_stopping.monitor,
                mode=params.early_stopping.mode,
                patience=params.early_stopping.patience,
                min_delta=params.early_stopping.min_delta, # type: ignore
                verbose=params.early_stopping.verbose,
                start_from_epoch=params.early_stopping.start_from_epoch,
            )
        )
        
    if params.checkpoint.use_callback:
        callbacks.append(
            ModelCheckpoint(
                filepath=str(checkpoint_path) if checkpoint_path is not None else None,
                monitor=params.checkpoint.monitor,
                mode=params.checkpoint.mode,
                save_best_only=params.checkpoint.save_best_only,
                save_weights_only=params.checkpoint.save_weights_only,
            )
        )
        
    if params.reduce_lr.use_callback:
        callbacks.append(
            ReduceLROnPlateau(
                monitor=params.reduce_lr.monitor,
                mode=params.reduce_lr.mode,
                factor=params.reduce_lr.factor,
                patience=params.reduce_lr.patience,
                min_lr=params.reduce_lr.min_lr,
                min_delta=params.reduce_lr.min_delta,
                verbose=params.reduce_lr.verbose,
            )
        )
        
    if params.static_logger.use_callback:
        logging_steps = len(train_dataset) // params.static_logger.batch_logging_steps if params.static_logger.batch_logging_steps is not None else 0
        callbacks.append(
            StaticProgressLogger(
                batch_logging=params.static_logger.batch_logging,
                batch_logging_steps=logging_steps,
            )
        )
    
    if params.use_weight_monitor:
        callbacks.append(WeightMonitor())

    if extra_callbacks is not None:
        callbacks.extend(extra_callbacks)
    
    return callbacks

def train_network(
    model: Model,
    checkpoint_path: Path,
    train_data: Union[EmbeddingSequenceMultiPerc, Dataset],
    validation_data: Union[EmbeddingSequenceMultiPerc, Dataset, None] = None,
    epochs: int = 50,
    verbose: Union[int, str] = 0,
    callback_params: Union[CallbackParams, None] = None,
    extra_callbacks: list | None = None,
) -> dict:
    """
    Execute the training loop for the Visual GRNet model.

    Resolves operational callbacks using configuration dataclasses, binds target paths 
    for monitoring checkpoint savings, and invokes the underlying framework optimization 
    pass configuration.

    Parameters
    ----------
    model : keras.models.Model
        The instantiated Visual GRNet network instance to train.
    checkpoint_path : pathlib.Path
        The destination directory path targeted for saving optimal model instances.
    train_data : EmbeddingSequenceMultiPerc or tf.data.Dataset
        The active data stream provider tracking training mini-batches.
    validation_data : EmbeddingSequenceMultiPerc, tf.data.Dataset or None, default None
        The out-of-sample verification dataset stream used to validate model generalization.
        If None, validation checks are skipped.
    epochs : int, default 50
        The maximum number of training cycles to execute.
    verbose : int or str, default 0
        The verbosity mode log layout configuration passed to the model compilation runner.
    callback_params : Optional[CallbackParams], default None
        Dataclass coordinating early stopping boundaries, logs, and checkpoints.
    extra_callbacks : Optional[list], default None
        Optional collection of custom external callbacks appended to the execution context.

    Returns
    -------
    dict
        A dictionary mapping containing sequential logs of training and validation metrics 
        recorded across epochs (`history.history`).
    """    
    if callback_params is None:
        callback_params = CallbackParams()
    
    callbacks = _build_callbacks(
        checkpoint_path=checkpoint_path,
        train_dataset=train_data,
        params=callback_params,
        extra_callbacks=extra_callbacks
    )

    history = model.fit(
        x=train_data,
        validation_data=validation_data,
        epochs=epochs,
        verbose=verbose, # type: ignore
        callbacks=callbacks
    )

    return history.history


def split_dataset_sequences(
    sequences: List[Path], 
    image_params: dict, 
    dizionario_goal: dict, 
    goals: dict, 
    min_percentage: float, 
    max_percentage: float, 
    batch_size: int, 
    max_dim: int, 
    ignore_last_n_states: int = 2, 
    validation_split: float = 0.15, 
    seed: int = 42, 
    train: bool = False, 
    test: bool = False
) -> tuple:
    """
    Partition raw plan sequence image directories into training, validation, and testing splits.

    Shuffles incoming filesystem paths deterministically using a localized random seed generator, 
    allocates discrete subsets according to a split ratio configuration, and returns compiled 
    TensorFlow dataset pipelines.

    .. note::
       This component is part of the legacy image-based framework pipeline. It has been 
       superseded by `get_train_validation_split_embeddings` to eliminate raw image I/O overhead.

    Parameters
    ----------
    sequences : list of pathlib.Path
        A collection of directory paths containing the sequence images to partition.
    image_params : dict
        Dictionary tracking target geometry metadata fields including 'width', 'height', and 'channels'.
    dizionario_goal : dict of (str, int)
        A lookup mapping translating uppercase goal fluent strings to unique vector indices.
    goals : dict of (str, list of str)
        A dictionary mapping base problem identifiers to their corresponding list of active subgoals.
    min_percentage : float
        The lower bound percentage threshold governing the dynamic continuous uniform sampling window.
    max_percentage : float
        The upper bound percentage threshold governing the dynamic continuous uniform sampling window.
    batch_size : int
        The size configuration specifying how many samples to pack per mini-batch.
    max_dim : int
        The maximum allowed sequence length acting as the padding or truncation boundary.
    ignore_last_n_states : int, default 2
        The count of terminal sequence frames to drop before sampling.
    validation_split : float, default 0.15
        The fractional split ratio used to calculate validation and test partition boundaries. 
        Allocates `validation_split` for verification and an equal amount for testing.
    seed : int, default 42
        The random seed enforcing repeatable deterministic partition shuffling distributions.
    train : bool, default False
        If True, builds and returns functional training and validation image pipeline streams.
    test : bool, default False
        If True, builds and returns the designated functional testing image pipeline stream.

    Returns
    -------
    tuple
        A three-element tuple containing `(train_dataset, validation_dataset, test_dataset)`. 
        Unrequested streams or inactive conditional branches are returned as None entries.
    """
    num_sequences = len(sequences)
    num_validation = int(num_sequences * validation_split)
    num_test = num_validation
    num_train = num_sequences - num_validation - num_test

    rng = random.Random(seed)
    rng.shuffle(sequences)

    train_sequences = sequences[:num_train]
    validation_sequences = sequences[num_train:num_train + num_validation]
    test_sequences = sequences[num_train + num_validation:]

    common_args = {
        'image_width': image_params['width'],
        'image_height': image_params['height'],
        'channels': image_params['channels'],
        'dizionario_goal': dizionario_goal,
        'goals': goals,
        'batch_size': batch_size,
        'max_dim': max_dim,
        'min_perc': min_percentage,
        'max_perc': max_percentage,
        'ignore_last_n_states': ignore_last_n_states,
    }

    if train:
        train_dataset = SequenceDatasetMultiPerc(sequences=train_sequences, **common_args).build_dataset()
        validation_dataset = SequenceDatasetMultiPerc(sequences=validation_sequences, **common_args).build_dataset()
        test_dataset = None
    elif test:
        train_dataset = validation_dataset = None
        test_dataset = SequenceDatasetMultiPerc(sequences=test_sequences, **common_args).build_dataset()
    else:
        train_dataset = test_dataset = validation_dataset = None

    return train_dataset, validation_dataset, test_dataset


def get_train_validation_split_embeddings(
    train_path: Union[str, Path, None], 
    validation_path: Union[str, Path, None], 
    max_dim: int, 
    min_percentage: float, 
    max_percentage: float, 
    batch_size: int, 
    embedding_dim: int, 
    num_classes: int, 
    ignore_last_n_states: int = 2, 
    norm_mean: Union[np.ndarray, None] = None, 
    norm_std: Union[np.ndarray, None] = None,
    limit: Union[float, None] = None,
) -> tuple[Union[EmbeddingSequenceMultiPerc, None], Union[EmbeddingSequenceMultiPerc, None]]:
    """
    Instantiate embedding sequence data loaders for training and validation cycles.

    Unpacks structural arguments to construct separate custom Keras sequence stream 
    generators tracking out-of-sample data points. Applies uniform randomized percentage 
    horizons to individual samples at runtime.

    Parameters
    ----------
    train_path : str, pathlib.Path or None
        The file path targeting the compressed precomputed training embeddings archive (.npz).
    validation_path : str, pathlib.Path or None
        The file path targeting the compressed precomputed validation embeddings archive (.npz).
    max_dim : int
        The maximum allowed sequence length acting as the padding or truncation boundary.
    min_percentage : float
        The lower bound percentage threshold governing the randomized uniform sampling window.
    max_percentage : float
        The upper bound percentage threshold governing the randomized uniform sampling window.
    batch_size : int
        The size configuration specifying how many samples to pack per mini-batch.
    embedding_dim : int
        The operational feature dimensionality of the input embedding vectors.
    num_classes : int
        The total dimensionality of the target goal vector space.
    ignore_last_n_states : int, default 2
        The count of terminal sequence frames to discard before sampling.
    norm_mean : Optional[np.ndarray], default None
        Empirical feature-wise mean vector used to center the input distributions.
    norm_std : Optional[np.ndarray], default None
        Empirical feature-wise standard deviation vector used to stabilize input variances.
    limit : Optional[float], default None
        The fraction coefficient used to downsample the loaded sequence arrays for rapid tuning.

    Returns
    -------
    tuple
        A pair tuple containing `(train_dataset, validation_dataset)`. Elements evaluate to 
        None if their respective path argument is missing.
    """    
    common_args = {
        'max_dim': max_dim,
        'min_perc': min_percentage,
        'max_perc': max_percentage,
        'ignore_last_n_states': ignore_last_n_states,
        'embedding_dim': embedding_dim,
        'num_classes': num_classes,
        'batch_size': batch_size,
        'norm_mean': norm_mean,
        'norm_std': norm_std,
        'limit': limit
    }

    train_dataset = EmbeddingSequenceMultiPerc(npz_path=train_path, **common_args) if train_path is not None else None
    validation_dataset = EmbeddingSequenceMultiPerc(npz_path=validation_path, **common_args) if validation_path is not None else None

    return train_dataset, validation_dataset


def get_test_dataset(
    test_path: Union[str, Path, None], 
    max_dim: int, 
    percentage: float, 
    batch_size: int, 
    embedding_dim: int, 
    num_classes: int, 
    ignore_last_n_states: int = 2, 
    norm_mean: Union[np.ndarray, None] = None, 
    norm_std: Union[np.ndarray, None] = None,
) -> EmbeddingSequence:
    """
    Instantiate an EmbeddingSequence data loader tailored for model inference testing phases.

    Enforces a strict fixed percentage observation threshold constraint across all processed 
    sequences, preventing stochastic variations to ensure reliable evaluation metrics tracking.

    Parameters
    ----------
    test_path : str, pathlib.Path or None
        The file path targeting the compressed precomputed testing embeddings archive (.npz).
    max_dim : int
        The maximum allowed sequence length acting as the padding or truncation boundary.
    percentage : float
        The constant observation window sequence fraction applied uniformly across test files.
    batch_size : int
        The size configuration specifying how many samples to pack per mini-batch.
    embedding_dim : int
        The operational feature dimensionality of the input embedding vectors.
    num_classes : int
        The total dimensionality of the target goal vector space.
    ignore_last_n_states : int, default 2
        The count of terminal sequence frames to discard before sampling.
    norm_mean : Optional[np.ndarray], default None
        Empirical Z-score centering shift array matching input dimension shapes.
    norm_std : Optional[np.ndarray], default None
        Empirical Z-score scaling variance normalization array matching input dimension shapes.

    Returns
    -------
    EmbeddingSequence
        An operational fixed-percentage dataset stream loader instance configured for inference loops.

    Raises
    ------
    ValueError
        If `test_path` evaluates to None or is not provided.
    """    
    if test_path is None:
        raise ValueError('Test dataset path not provided')
    
    return EmbeddingSequence(
        npz=test_path,
        max_dim=max_dim,
        batch_size=batch_size,
        embedding_dim=embedding_dim,
        num_classes=num_classes,
        ignore_last_n_states=ignore_last_n_states,
        norm_mean=norm_mean,
        norm_std=norm_std,
        perc=percentage
    )


def get_trained_model(model_path: Path) -> Model:
    """
    Load a pre-trained Visual GRNet model checkpoint from disk storage.

    Registers required domain-specific operational custom structures (AttentionWeights, 
    ContextVector) to safely restore model architectures without compilation requirements.

    Parameters
    ----------
    model_path : pathlib.Path
        The absolute disk file path targeting the serialized Keras (.keras) model artifact.

    Returns
    -------
    keras.models.Model
        The instantiated trained model recovered from storage.
    """
    print('Loading model')
    model:Model = load_model(
        model_path,
        custom_objects={
            'AttentionWeights': AttentionWeights,
            'ContextVector': ContextVector,
        },
        compile=False
    ) # type: ignore
    return model 


def get_model_predictions(model: Model, test_dataset: Union[Dataset, EmbeddingSequence], verbose: Union[str, int] = 0) -> tuple[np.ndarray, np.ndarray]:
    """
    Compute forward pass matrix predictions and aggregate ground truth target arrays.

    Iterates through mini-batches provided by the data streaming wrapper to safely unpack 
    and concatenate categorical multidimensional labels before executing network predictions.

    Parameters
    ----------
    model : keras.models.Model
        The trained sequence classification network used to execute the forward pass.
    test_dataset : tf.data.Dataset or EmbeddingSequence
        The streaming interface supplying evaluation sequence and target target pairs.
    verbose : int or str, default 0
        The verbosity logging layout mode configuration forwarded to the predict loop.

    Returns
    -------
    y_pred : np.ndarray
        A 2D float32 array tracking predicted network cross-entropy confidence distributions.
    y_true : np.ndarray
        A 2D int32 array collecting unified matching multi-hot ground truth labels.
    """    
    def _get_numpy(y) -> np.ndarray:
        return y.numpy() if not isinstance(y, np.ndarray) else y

    y_true = np.concatenate([_get_numpy(y_batch) for _, y_batch in test_dataset], axis=0).astype(int)
    print(f"Total positive activations in evaluation subset: {y_true.sum()}")
    
    y_pred = model.predict(test_dataset, verbose=verbose).astype(np.float32) # type: ignore
    return y_pred, y_true


def evaluate(y_pred: np.ndarray, y_true: np.ndarray, threshold: float = 0.5, print_results: bool = False) -> dict:
    """
    Evaluate multi-label sequence classification performance across multiple core metrics.

    Applies a hard binarization decision boundary threshold to output continuous distributions,
    computing exact match criteria, dimension-wise label correctness, and macro-averaged 
    precision, recall, and F1 configurations.

    Parameters
    ----------
    y_pred : np.ndarray
        A 2D array tracking the predicted confidence coordinates mapping target classes.
    y_true : np.ndarray
        A 2D multi-hot array tracking true target goal intersections.
    threshold : float, default 0.5
        The hard logical activation scalar threshold separating negative and positive states.
    print_results : bool, default False
        If True, outputs a formatted performance breakdown table to standard output.

    Returns
    -------
    dict
        A summary dictionary mapping calculated classification performance criteria.
    """    
    y_bin = (y_pred >= threshold).astype(int)

    metrics = {
        'exact_accuracy':      accuracy_score(y_true, y_bin),
        'mean_label_accuracy': (y_true == y_bin).mean(axis=0).mean(),
        'precision_macro':     precision_score(y_true, y_bin, average='macro', zero_division=0),
        'recall_macro':        recall_score(y_true, y_bin, average='macro', zero_division=0),
        'f1_macro':            f1_score(y_true, y_bin, average='macro', zero_division=0),
        'pr_auc_macro':        average_precision_score(y_true, y_pred, average=None).mean(), # type: ignore
        'avg_true_positive':   y_true.sum(axis=1).mean(),
        'avg_pred_positive':   y_bin.sum(axis=1).mean(),
    }

    if print_results:
        print(f'Metrics (threshold={threshold})')
        print('-' * 60)
        print(f"Exact match accuracy:\t{metrics['exact_accuracy']:.4f}")
        print(f"Mean label accuracy:\t{metrics['mean_label_accuracy']:.4f}")
        print(f"Precision (macro):\t{metrics['precision_macro']:.4f}")
        print(f"Recall (macro):\t\t{metrics['recall_macro']:.4f}")
        print(f"F1 (macro):\t\t{metrics['f1_macro']:.4f}")
        print(f"PR-AUC (macro):\t\t{metrics['pr_auc_macro']:.4f}")
        print(f"\nMean true positives per sample:      {metrics['avg_true_positive']:.2f}")
        print(f"Mean predicted positives per sample: {metrics['avg_pred_positive']:.2f}")

    return metrics


def get_bias_initialization(y_train: np.ndarray) -> np.ndarray: 
    """
    Derive optimal base frequency prior logit biases to stabilize network initialization.

    Calculates sample-wise positive activation frequencies across training sets and applies 
    the inverse sigmoid mapping transformation. This initialization guarantees that early cross-entropy 
    gradients reflect empirical label distributions, accelerating convergence in imbalanced setups.

    Parameters
    ----------
    y_train : np.ndarray
        A 2D training target array tracking historical multi-hot label intersections.

    Returns
    -------
    np.ndarray
        A 1D float32 log-odds bias array of shape (num_classes,) used to initialize output Dense layers.
    """
    print('Extracting empirical distribution prior bias initialization...')
    pos_freq = np.mean(y_train, axis=0)  
    
    # Clippa i limiti numerici per evitare errori di instabilità matematica log(0) o divisioni per zero
    pos_freq = np.clip(pos_freq, 1e-7, 1.0 - 1e-7)
    bias_init = np.log(pos_freq / (1.0 - pos_freq))
    return bias_init


@register_keras_serializable()
class WeightedBCE(Loss):
    """
    Custom frequency-weighted Binary Cross-Entropy loss for backend-agnostic Keras 3.

    Balances binary classification objective functions by scaling positive and negative losses 
    separately based on empirical class distribution ratios. This prevents dominant negative labels 
    from washing out scarce positive signals in sparse multi-hot spaces.

    Parameters
    ----------
    pos_weights : np.ndarray
        A 1D array of shape (num_classes,) containing penalty scalars applied to positive misses.
    neg_weights : np.ndarray
        A 1D array of shape (num_classes,) containing penalty scalars applied to negative misses.
    name : str, default "weighted_bce"
        The organizational string identifier tagging the structural loss instance.
    """
    def __init__(
        self,
        pos_weights: np.ndarray,  
        neg_weights: np.ndarray,
        name: str = "weighted_bce",
        **kwargs
    ):
        super().__init__(name=name, **kwargs)
        self.pos_weights = pos_weights  
        self.neg_weights = neg_weights
        self._pos_weights_tensor = ops.convert_to_tensor(pos_weights, dtype='float32')  
        self._neg_weights_tensor = ops.convert_to_tensor(neg_weights, dtype='float32')  

    def call(self, y_true: tf.Tensor, y_pred: tf.Tensor) -> tf.Tensor:
        """
        Compute the dynamic objective loss tensor mapping input batch matrices.

        Parameters
        ----------
        y_true : tf.Tensor
            The target true classification matrix tracking multi-hot ground truth labels.
        y_pred : tf.Tensor
            The network forward pass continuous output logit activation matrix.

        Returns
        -------
        tf.Tensor
            A scalar tensor tracking the aggregated weighted categorical cross-entropy loss value.
        """
        y_true = ops.cast(y_true, 'float32') # type: ignore
        y_pred = ops.cast(y_pred, 'float32') # type: ignore
        
        y_pred = ops.clip(y_pred, 1e-7, 1.0 - 1e-7) # type: ignore

        bce = -(
            self._pos_weights_tensor * y_true * ops.log(y_pred)
            + self._neg_weights_tensor * (1.0 - y_true) * ops.log(1.0 - y_pred)
        )
        return ops.mean(bce) # type: ignore

    def get_config(self) -> dict:
        """
        Serialize the class configuration parameters into standard Python datatypes.

        Returns
        -------
        dict
            A tracking key-value dictionary containing serialized loss parameters.
        """
        config = super().get_config()
        config.update({
            "pos_weights": self.pos_weights.tolist(), 
            "neg_weights": self.neg_weights.tolist(),
        })
        return config

    @classmethod
    def from_config(cls, config: dict) -> 'WeightedBCE':
        """
        Instantiate an identical operational object recovery layout from configuration maps.

        Parameters
        ----------
        config : dict
            The key-value parameters dictionary retrieved from the serialization parser.

        Returns
        -------
        WeightedBCE
            A fully restored, operational custom Loss instance.
        """
        config["pos_weights"] = np.array(config["pos_weights"])  
        config["neg_weights"] = np.array(config["neg_weights"])
        return cls(**config)
    

def calculate_frequencies(label_npz: Union[str, Path]) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract dimensional positive and negative prior occurrence frequencies from an NPZ file.

    Loads a compressed training archive, reconstructs stacked multi-hot training targets, 
    and applies axis-wise counts to determine structural scaling constants for balanced training.

    Parameters
    ----------
    label_npz : str or pathlib.Path
        The filepath pointing to the compressed precomputed training embeddings archive.

    Returns
    -------
    positive_frequencies : np.ndarray
        A 1D array tracking the fractional occurrence rate of positive labels per class dimension.
    negative_frequencies : np.ndarray
        A 1D array tracking the fractional occurrence rate of negative labels per class dimension.
    """
    train_embeddings = np.load(label_npz)
    
    # Vectorized list comprehension mapping to optimize memory allocations over historical iterations
    labels = np.stack([train_embeddings[f'goal_{seq}'] for seq in train_embeddings['seq_names']])
    n_samples = labels.shape[0]
    
    positive_frequencies = np.sum(labels, axis=0) / n_samples  
    negative_frequencies = 1.0 - positive_frequencies   

    return positive_frequencies, negative_frequencies